### ISSUE TITLE
enhanced address is being used from node to local pods unexpectedlly

### ISSUE THREAD

**Issue by mars1024** [alibaba/hybridnet#232]
Bug Report
---

Type: *bug report*

### What happened

![image](https://user-images.githubusercontent.com/15814167/165010410-6117343a-02e8-41df-a542-5e2ea97dd187.png)

![image](https://user-images.githubusercontent.com/15814167/165010444-11f62a52-ba9d-4dd4-9c03-a5476fc87c62.png)

Enhanced address is being used, when we want to ping local pods from node. This will cause the ICMP reply will never come back.

### Environment
- hybridnet version: 3.2.0
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Kubernetes version:
- Install tools:
- Others:

**Comment by hhyasdf** [comment]
Related to #31

**Comment by hhyasdf** [comment]
Actually, the problem is that the "enhanced address" used for vlan arp enhancement will be selected as source address for host traffic sometimes. But we just need it to be the source address for pod traffic.

We need to find a way to prevent enhanced addresses from source address selection for the host traffic.
